Soyun
ConconDev/backend pull request #35
Opened 2024-09-21 08:49 UTC by kingwhangzang

2024-09-21 10:00 UTC, osjkate requested changes

2024-09-22 05:48 UTC, kingwhangzang commented on src/main/resources/application.properties
> +spring.mvc.pathmatch.matching-strategy=ant_path_matcher
이건 삭제했슴당

2024-09-22 05:48 UTC, kingwhangzang commented on src/main/java/com/sookmyung/concon/Review/service/ReviewService.java
> +    private void saveReviewToDatabase(Review review) {
추가했습니당

2024-09-22 05:55 UTC, kingwhangzang commented on src/main/java/com/sookmyung/concon/Review/entity/Review.java
> +    private Long userId; // User ID를 저장
이거 내 브렌치 코드 보면 다르거든? 그거 확인 부탁드려용

2024-09-22 05:57 UTC, kingwhangzang commented on src/main/java/com/sookmyung/concon/Review/controller/ReviewController.java
> +        Review review = Review.builder()
이거는 혹시 무슨 말일까요? ReviewRequest 라는 dto를 만들어서 코드 작성했는데, 이걸 그냥 createReview(reviewRequest)로 변경하라는건가요?

2024-09-22 06:05 UTC, osjkate requested changes

2024-09-22 06:05 UTC, osjkate commented on src/main/java/com/sookmyung/concon/Review/controller/ReviewController.java
> +        reviewService.createReview(review);
여기서 서비스 단에 dto 형식으로 보내고 엔티티 생성하는 코드 (builder 코드를 서비스 안에서 처리하라는 뜻!)
reviewService.createReview(dto) 일케 보내서

2024-09-22 06:34 UTC, closed without merging